const types = {
  // auth user
  AUTH_USER: 'AUTH_USER',
  SIGN_UP_USER: 'SIGN_UP_USER',
  SIGN_IN_USER: 'SIGN_IN_USER',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  // companies
  GET_ACCOUNTS: 'GET_ACCOUNTS',
  GET_ACCOUNTS_BEGIN: 'GET_ACCOUNTS_BEGIN',
  GET_ACCOUNTS_SUCCESS: 'GET_ACCOUNTS_SUCCESS',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
}

export default types;